# Generated by Django 5.0.2 on 2024-03-04 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartUsers.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='main_cover/')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isAvailable', models.BooleanField(default=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('isApproved', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartUsers.category')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartUsers.tutorprofile')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartUsers.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumb/')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_file/')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('request', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved')], max_length=20, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartUsers.course')),
            ],
        ),
    ]
