# Generated by Django 5.0.2 on 2024-03-05 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartUsers', '0003_remove_tutorprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TutorProfile',
        ),
    ]
